### ISSUE TITLE
Compatibility width Symfony 6 ?

### ISSUE THREAD

**Issue by webagil-kevin** [umanit/easyadmin-tree-bundle#1]
Hi,

It's not possible to install with composer.

My config : 
- Symfony 6.1
- Easyadmin-tree-bundle 0.0.3

Error:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires umanit/easyadmin-tree-bundle ^0.0.3 -> satisfiable by umanit/easyadmin-tree-bundle[0.0.3].
    - umanit/easyadmin-tree-bundle 0.0.3 requires symfony/config ^5.4 -> found symfony/config[v5.4.0, ..., v5.4.11] but these were not loaded, likely because it conflicts with another require.
```

Thank you for this project and the next update, future features are great.

**Comment by jodou92** [comment]
Hello,

Thanks for your support. I just pushed a new version (0.0.4) which should be suitable for v6.* versions of Symfony ;)
